M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, 01 November 2023 at 15:03:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-01T15:03:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X179.542Y-43.458
T2
X105.2Y-69.9
X150.54Y-68.23
X179.6Y-106.09
X191.96Y-28.79
T3
X116.012Y-43.458
X171.212Y-27.458
T0
M30
